### ISSUE TITLE
oops error

### ISSUE THREAD

**Issue by mmsaberi** [Alireaza00/Abasaleh-ERP#4]
جہاں تک مجھے سمجھ میں آیا ہے، جب بچوں کے پاس کارڈ نہیں ہوتے تھے (یعنی ھم نے انہیں کوئی کارڈ نہیں دیے ہوتے تھے) اور وہ خریدنے کی کوشش کرتے تھے تو یہ ایرر  آتا تھا۔
یہ ایرر بچوں نے ہمیں بھیجا ہے
![photo_2024-06-07_08-23-25](https://github.com/Alireaza00/Abasaleh-ERP/assets/171594314/9d976457-b121-4240-a321-f0d26d73dde6)

**Comment by Alireaza00** [comment]
unable to duplicate this bug as expressed with zero points user when try to buy it throws error so closing as its not confirmed or reproduced

**Comment by mmsaberi** [comment]
میں نہیں سمجھ پایا آپ کی مراد

**Comment by Alireaza00** [comment]
اسکا مطلب ہے کے ہم نے ایک یوزر جس کے زیرو پوانٹ تھے خریدنے کی کوسش کی کچھ پروڈکٹ تو ایسا کوئی بگ نہیں  آیا یا سمجیں پروڈیوس نہیں ہوا لہذا ہم اسے فکس کرنے سےقاصر ہیں.کسی بھی بگ کو فکس کرنے کے لیے پروڈیوس کرنا ضروری ہے ہم نے جب ٹسٹ کیا تو ایسا کوئی بگ ریکارڈ نہیں ہوا
